sonar.projectKey=food-ordering-system
sonar.projectName=Food Ordering System
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12

sonar.exclusions=venv/**,__pycache__/**,tests/**,static/**

sonar.host.url=http://localhost:9000